name: fleet_tracker
description: A new Flutter project.
version: 1.0.0+1

environment:
  sdk: '>=3.0.5 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  fluttertoast: ^8.2.6
  flutter_gen_runner: ^5.5.0+1
  go_router: ^14.1.4
  provider: ^6.1.2
  flutter_riverpod: ^2.5.1
  firebase_core: ^3.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0
  build_runner: ^2.4.9
  go_router_builder: ^2.6.2

flutter_gen:
  colors:
    inputs:
      - assets/color/colors.xml

flutter:
  uses-material-design: true

  assets:
    - assets/images/
    - assets/images/top_loading/
