name: fleet_tracker
description: A new Flutter project.
version: 1.0.0+1

environment:
  sdk: '>=3.0.5 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  fluttertoast: ^8.2.6
  flutter_gen_runner: ^5.5.0+1
  go_router: ^14.1.4
  provider: ^6.1.2
  flutter_riverpod: ^2.5.1
  http: ^1.2.1
  firebase_core: ^3.0.0
  flutter_dotenv: ^5.1.0
  flutter_map: ^7.0.1
  latlong2: ^0.9.1
  background_task: ^0.1.1+1

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0
  build_runner: ^2.4.9
  go_router_builder: ^2.6.2

flutter_gen:
  colors:
    inputs:
      - assets/color/colors.xml
  assets:
    exclude:
      - .env.develop
      - .env.release

flutter:
  uses-material-design: true

  assets:
    - .env.develop
    - .env.release
    - assets/images/
    - assets/images/icons/
    - assets/images/top_loading/
    - assets/images/component/

  fonts:
    - family: Noto_Sans_JP
      fonts:
        - asset: assets/fonts/Noto_Sans_JP/NotoSansJP-Thin.otf
          weight: 100
        - asset: assets/fonts/Noto_Sans_JP/NotoSansJP-Light.otf
          weight: 300
        - asset: assets/fonts/Noto_Sans_JP/NotoSansJP-Regular.otf
          weight: 400
        - asset: assets/fonts/Noto_Sans_JP/NotoSansJP-Medium.otf
          weight: 500
        - asset: assets/fonts/Noto_Sans_JP/NotoSansJP-Bold.otf
          weight: 700
        - asset: assets/fonts/Noto_Sans_JP/NotoSansJP-Black.otf
          weight: 900
