// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCn0qdXxCOMOh_VljxIRIH_UMj7oH0SfvU',
    appId: '1:30635038276:web:39728dc88f24833a588e11',
    messagingSenderId: '30635038276',
    projectId: 'sei-zen-setsu',
    authDomain: 'sei-zen-setsu.firebaseapp.com',
    storageBucket: 'sei-zen-setsu.appspot.com',
    measurementId: 'G-HBQTG5MRNZ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBLzm3-71U4DgZRjMV8Xdgs4Xrz_PmpoRM',
    appId: '1:30635038276:android:640d554982f2ece1588e11',
    messagingSenderId: '30635038276',
    projectId: 'sei-zen-setsu',
    storageBucket: 'sei-zen-setsu.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDW0y0jJQsyKDgj3v3oJTSd6yiT4eo7XLg',
    appId: '1:30635038276:ios:21c9122d48adfd2e588e11',
    messagingSenderId: '30635038276',
    projectId: 'sei-zen-setsu',
    storageBucket: 'sei-zen-setsu.appspot.com',
    iosBundleId: 'jp.ac.hal.fleetTracker',
  );
}
